### PR TITLE
Support for subdirectories in java config.

### PR DESCRIPTION
**Pull request by colin-yell**

### CODE REVIEW

**Comment by dcarley** [comment]
Thanks for the prompt turn around. I'll merge as soon as I have a chance to test it against a few existing projects.

**Comment by mentzerk** [comment]
Looks good.

**Comment by scandian** [comment]
Pull request #11 was just merged, which made some changes in the same method. You probably need to rebase the changes in this PR before merging.

**Comment by dcarley** [comment]
Updated this and merged. Sorry for the delay.

**Pull request closed without merging**
