### PR TITLE
changes to make maven and java play nicer together with relative paths etc

### PR DESCRIPTION
**Pull request by wesamhaboush**

### CODE REVIEW

**Comment by mentzerk** [comment]
The diffs are a little confusing to follow, but it looks good.

**Comment by dcarley** [comment]
Do you have an example of a modified `fabfile.py` that you've been using with these changes?

I'm unsure about overriding some of the paths. Particularly those that come from `yellfabric.defaults`.

Out of interest, had you been using the `use_maven_build` task prior to this? I think it's closely related.

Lastly, there was talk a long time ago about moving to a proprer template engine. But I think we failed to arrive at a decision as to which one. I'm not fond of the variable interpolation we're currently doing. `string.Template` seems like a sensible choice, as we probably don't need a bells-and-whistle templating engine. We'd have to think about how we gradually move people towards that.

**Comment by wesamhaboush** [comment]
Cc:platform

Hi Dan,

Thanks for your response.

Find attached an example file as requested.

No, I have not been using the use_maven_build task prior to this. Is there any resources around this for me to look at?

With regard to overriding some of the paths. I largely agree with you that we need to preserve some system inner workings (sensible defaults). However, I think what I am trying to change is related to how we specify the files to be deployed from within the project, which we do now anyway. I think it is a good idea to let the yellfabric control the destination naming conventions (based on project name for example). However, the sources do not have to be. For example, someone may have the config files named differently (the tar). Or put in a different module within their project, etc. It is all about allowing the developers the flexibility to structure their project from a software engineering perspective as they see fit, and then linking that back to fabric through this flexible hooks as opposed to having to force their process of development to fit with fabric’s deployment mould if that makes sense.

Also notice that my changes are not backwards compatible with how the wars used to be deployed. So teams will have to change their fabs to accommodate this. However, I think it is too easy and too convenient in the very near future that they wouldn’t mind doing it. Also I would be more than happy to contribute time and effort towards the migration in collaboration with them. I can write a wiki on the subject if we get the go ahead from yourself.

With regard to the templating, I think I would be happy to help with that. It seems I am enjoying pythoning too much to let it go ☺. But I would like first to get some of the changes that I have already written through, and work on the templating issue afterwards. Of course all will be in close collaboration with your team given you are much closer to that side of things.

Kind Regards,
Sam

**Comment by wesamhaboush** [comment]
Hi Dan,

Any update with regard to the use-maven-build thing, and the changes that I have made?

Thanks,
Sam

From: Haboush, Wesam (UK)
Sent: 08 August 2012 07:42
To: 'YellLabs/yellfabric'; YellLabs/yellfabric
Cc: Carley, Dan (UK); OCarra, Maebh (UK); Sanchez-Ros, Eduardo (UK); Mortensen, Michael (UK); Sardar, Toqeer (UK); Lewis, Simon (UK)
Subject: RE: [yellfabric] changes to make maven and java play nicer together with relative paths etc (#7)

Cc:platform

Hi Dan,

Thanks for your response.

Find attached an example file as requested.

No, I have not been using the use_maven_build task prior to this. Is there any resources around this for me to look at?

With regard to overriding some of the paths. I largely agree with you that we need to preserve some system inner workings (sensible defaults). However, I think what I am trying to change is related to how we specify the files to be deployed from within the project, which we do now anyway. I think it is a good idea to let the yellfabric control the destination naming conventions (based on project name for example). However, the sources do not have to be. For example, someone may have the config files named differently (the tar). Or put in a different module within their project, etc. It is all about allowing the developers the flexibility to structure their project from a software engineering perspective as they see fit, and then linking that back to fabric through this flexible hooks as opposed to having to force their process of development to fit with fabric’s deployment mould if that makes sense.

Also notice that my changes are not backwards compatible with how the wars used to be deployed. So teams will have to change their fabs to accommodate this. However, I think it is too easy and too convenient in the very near future that they wouldn’t mind doing it. Also I would be more than happy to contribute time and effort towards the migration in collaboration with them. I can write a wiki on the subject if we get the go ahead from yourself.

With regard to the templating, I think I would be happy to help with that. It seems I am enjoying pythoning too much to let it go ☺. But I would like first to get some of the changes that I have already written through, and work on the templating issue afterwards. Of course all will be in close collaboration with your team given you are much closer to that side of things.

Kind Regards,
Sam

**Comment by wesamhaboush** [comment]
Dan,

Could you kindly provide an ETA?

Thanks,
Sam

From: Haboush, Wesam (UK)
Sent: 11 August 2012 16:10
To: 'YellLabs/yellfabric'; 'YellLabs/yellfabric'
Cc: Carley, Dan (UK); OCarra, Maebh (UK); Sanchez-Ros, Eduardo (UK); Mortensen, Michael (UK); Sardar, Toqeer (UK); Lewis, Simon (UK)
Subject: RE: [yellfabric] changes to make maven and java play nicer together with relative paths etc (#7)

Hi Dan,

Any update with regard to the use-maven-build thing, and the changes that I have made?

Thanks,
Sam

From: Haboush, Wesam (UK)
Sent: 08 August 2012 07:42
To: 'YellLabs/yellfabric'; YellLabs/yellfabric
Cc: Carley, Dan (UK); OCarra, Maebh (UK); Sanchez-Ros, Eduardo (UK); Mortensen, Michael (UK); Sardar, Toqeer (UK); Lewis, Simon (UK)
Subject: RE: [yellfabric] changes to make maven and java play nicer together with relative paths etc (#7)

Cc:platform

Hi Dan,

Thanks for your response.

Find attached an example file as requested.

No, I have not been using the use_maven_build task prior to this. Is there any resources around this for me to look at?

With regard to overriding some of the paths. I largely agree with you that we need to preserve some system inner workings (sensible defaults). However, I think what I am trying to change is related to how we specify the files to be deployed from within the project, which we do now anyway. I think it is a good idea to let the yellfabric control the destination naming conventions (based on project name for example). However, the sources do not have to be. For example, someone may have the config files named differently (the tar). Or put in a different module within their project, etc. It is all about allowing the developers the flexibility to structure their project from a software engineering perspective as they see fit, and then linking that back to fabric through this flexible hooks as opposed to having to force their process of development to fit with fabric’s deployment mould if that makes sense.

Also notice that my changes are not backwards compatible with how the wars used to be deployed. So teams will have to change their fabs to accommodate this. However, I think it is too easy and too convenient in the very near future that they wouldn’t mind doing it. Also I would be more than happy to contribute time and effort towards the migration in collaboration with them. I can write a wiki on the subject if we get the go ahead from yourself.

With regard to the templating, I think I would be happy to help with that. It seems I am enjoying pythoning too much to let it go ☺. But I would like first to get some of the changes that I have already written through, and work on the templating issue afterwards. Of course all will be in close collaboration with your team given you are much closer to that side of things.

Kind Regards,
Sam

**Comment by dcarley** [comment]
I've split the templating changes out to a revised PR #8. Hadn't originally realised the priority of that part. Sam has given those the nod. Just needs review from the rest of our team.

I'm going to shelve the path changes for now. We're agreed that they should be largely surplus to use once we have a revised repo fetch task. Closing this PR.

**Pull request closed without merging**
