### PR TITLE
Added boto (aws sdk) as a python requirement

### PR DESCRIPTION
**Pull request by eazynow**
Have added in boto http://boto.readthedocs.org/en/latest/index.html as a requirement. 

This allows us to use it in our fabfile custom tasks without needing extra requirements per project.

### CODE REVIEW

**Comment by eazynow** [comment]
travis failed due to pylint not being found on build 23, but passed on build 22 (should be same thing?)

**Comment by mentzerk** [comment]
Curious to know the use case for these libs.  Also, travis seems intermittently grumpy with this addition.

**Comment by eazynow** [comment]
Kevin, I'm in the process of putting some fabric tasks together to query aws/control. 

It's to provide a better way of starting/stopping instance/environment etc. 

The work-in-progress code is at https://github.com/YellLabs/hibuvoice-web/blob/aws_deploy/aws.py

It's under hibuvoice for now but I'd see it being a more general util set in the end, perhaps even in yellfabric.

re:travis - not sure why it's grumpy. It was fine on build 22. boto is the package that amazon recommend to use with Python.

**Comment by mentzerk** [comment]
I don't have access to that repo, I'm afraid.  Also, I'm curious what your plans are for an internal deployment?  While I do agree that we need to be much faster on our delivery of app platforms and infrastructure, I'm not a huge fan of coupling them at the yellfabric level - especially if we are binding ourselves to a specific vendor.  The whole point of a cloud is not needing to worry which infrastructure you are using (be that internal, external EC2, external Rackspace, external whatever the next big thing is, etc).  If there is a need to have an api layer to control the infrastructure, I'd ask you to pull us into the conversation and see if we can provide some form of multi-platform abstraction layer (like delta cloud or something similar), rather than just coding for a single API.

**Pull request closed without merging**
